# Generated by Django 4.0.5 on 2022-09-01 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('body', mdeditor.fields.MDTextField()),
                ('image', models.ImageField(upload_to='myblog_image')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('d', 'draft'), ('s', 'special'), ('n', 'normal')], max_length=20)),
                ('film', models.FileField(blank=True, null=True, upload_to='myblog_film')),
                ('music', models.FileField(blank=True, null=True, upload_to='myblog_music')),
                ('published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myblog_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nums', to='appblog.myblog')),
                ('view', models.ManyToManyField(blank=True, related_name='view', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
