# Generated by Django 4.0.5 on 2022-09-18 08:28

from django.conf import settings
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
        ('appblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='category',
            field=models.ManyToManyField(related_name='myblog_categorys', to='blog.category'),
        ),
        migrations.AddField(
            model_name='myblog',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='myblog_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='myblog',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='myblog_saved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='myblog',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
