# Generated by Django 4.0.5 on 2022-09-18 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('familie', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=11)),
                ('gender', models.CharField(choices=[('m', 'man'), ('w', 'wonamn')], max_length=200)),
                ('date_of_birth', models.DateField()),
                ('national_code', models.CharField(max_length=10)),
                ('date_special', models.DateField(blank=True, null=True)),
                ('is_seller', models.BooleanField(default=False)),
                ('is_special', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=200)),
                ('shaba_number', models.CharField(max_length=24)),
                ('shop_number', models.CharField(choices=[('1', '1-10'), ('2', '10-100'), ('3', '100-1000')], max_length=200)),
                ('shop_type', models.CharField(choices=[('hko', 'خوراکی'), ('kha', 'خانگی'), ('b', 'برقی'), ('e', 'الکترونیکی'), ('gh', 'قیره')], max_length=200)),
                ('tax', models.DateField(blank=True, null=True)),
                ('national_card', models.ImageField(upload_to='')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_seller_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanySeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_type', models.CharField(choices=[('d', 'تجاری'), ('s', 'قیر تجاری'), ('n', 'شخصی')], max_length=200)),
                ('fixed_number', models.CharField(max_length=11)),
                ('economic_code', models.CharField(max_length=11)),
                ('permission_to_sign', models.CharField(max_length=11)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_seller_company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
