# Generated by Django 3.2 on 2023-03-06 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('address', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prodact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=200)),
                ('shaba_nmber', models.CharField(max_length=24)),
                ('shop_number', models.CharField(choices=[('1', '1-10'), ('2', '10-100'), ('3', '100-1000')], max_length=200)),
                ('shop_type', models.CharField(choices=[('hko', 'خوراکی'), ('kha', 'خانگی'), ('b', 'برقی'), ('e', 'الکترونیکی'), ('gh', 'قیره')], max_length=200)),
                ('tax', models.DateField(blank=True, null=True)),
                ('national_card', models.ImageField(upload_to='')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_seller_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProdactSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField(blank=True)),
                ('number', models.PositiveIntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_address_seller', to='address.address')),
                ('prodact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_blog', to='prodact.prodact')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-price'],
            },
        ),
        migrations.CreateModel(
            name='CompanySeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_type', models.CharField(choices=[('d', 'تجاری'), ('s', 'قیر تجاری'), ('n', 'شخصی')], max_length=200)),
                ('fixed_number', models.CharField(max_length=11)),
                ('economic_code', models.CharField(max_length=11)),
                ('permission_to_sign', models.CharField(max_length=11)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_seller_company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ColorNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('nums', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('published', models.BooleanField(default=False)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors_num', to='base.colors')),
                ('prodact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_num', to='prodact.prodact')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='num_seller', to='seller.prodactseller')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_num', to='base.sizes')),
            ],
        ),
    ]
