# Generated by Django 3.2 on 2023-03-06 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sagestion', models.CharField(choices=[('y', 'yes'), ('i', 'I do not know'), ('n', 'no')], max_length=50)),
                ('score', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50)),
                ('titel', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='coments_media')),
                ('date', models.DateField(auto_now_add=True)),
                ('bad', models.TextField()),
                ('good', models.TextField()),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ComentsBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Custion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('published', models.BooleanField(default=False)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes_custion', to=settings.AUTH_USER_MODEL)),
                ('one_respones', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_custion', to='coment.custion')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
