# Generated by Django 3.2 on 2023-03-06 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prodact', '0001_initial'),
        ('blog', '0001_initial'),
        ('coment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='custion',
            name='prodact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custion', to='prodact.prodact'),
        ),
        migrations.AddField(
            model_name='custion',
            name='tow_respones',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tow_custion', to='coment.custion'),
        ),
        migrations.AddField(
            model_name='custion',
            name='unlikes',
            field=models.ManyToManyField(blank=True, related_name='unlides_custion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='custion',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_custion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentsblog',
            name='appblog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coments_myblog', to='blog.blog'),
        ),
        migrations.AddField(
            model_name='comentsblog',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='coments_likes_blog', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentsblog',
            name='unlikes',
            field=models.ManyToManyField(blank=True, related_name='coments_unlides_blog', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentsblog',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='coments_user_blog', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coments',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='coments_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coments',
            name='prodact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coments_blog', to='prodact.prodact'),
        ),
        migrations.AddField(
            model_name='coments',
            name='unlikes',
            field=models.ManyToManyField(blank=True, related_name='coments_unlides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coments',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='coments_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
