# Generated by Django 3.2 on 2023-03-06 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('body', mdeditor.fields.MDTextField()),
                ('image', models.ImageField(upload_to='myblog_image')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('d', 'draft'), ('s', 'special'), ('n', 'normal')], max_length=20)),
                ('film', models.FileField(blank=True, null=True, upload_to='myblog_film')),
                ('music', models.FileField(blank=True, null=True, upload_to='myblog_music')),
                ('published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myblog_seller', to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(related_name='myblog_categorys', to='base.Category')),
                ('likes', models.ManyToManyField(blank=True, related_name='myblog_likes', to=settings.AUTH_USER_MODEL)),
                ('saved', models.ManyToManyField(blank=True, related_name='myblog_saved', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Nums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nums', to='blog.blog')),
                ('view', models.ManyToManyField(blank=True, related_name='view', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
