# Generated by Django 3.2 on 2023-03-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('online', models.BooleanField(default=True)),
                ('ordered', models.BooleanField(default=False)),
                ('cancel', models.BooleanField(default=False)),
                ('destroyed', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('current', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField()),
            ],
        ),
    ]
